name: SKYDEV Post Engine

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Operasi: GET (Ambil Data) atau LIKE (Eksekusi)'
        required: true
        default: 'GET'
      target_data:
        description: 'UUID User (GET) atau Kumpulan Post ID (LIKE)'
        required: true
      jumlah_bot:
        description: 'Jumlah Bot (Hanya dipakai untuk mode LIKE)'
        required: false
        default: '50'

jobs:
  operasi_postingan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Ambil Kode Repo
        uses: actions/checkout@v4
        
      - name: Siapkan Mesin Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Senjata (Dependencies)
        # Menambahkan paket aiofiles untuk menunjang performa V2 Async
        run: pip install curl_cffi requests aiofiles
        
      - name: Tembak Server PK XD
        run: python like_cloud.py ${{ github.event.inputs.mode }} "${{ github.event.inputs.target_data }}" ${{ github.event.inputs.jumlah_bot }}
        
      - name: Simpan Hasil Kerja ke GitHub
        run: |
          git config --global user.name "SKYDEV Automasi"
          git config --global user.email "bot@skydev.id"
          
          # Daftarkan berkas JSON (Hasil Mode GET), Sesi Aktif, dan HISTORY LIKE
          git add BOT/Temp/latest_posts.json || true
          git add BOT/Akun_Baru/ActiveSessions.txt || true
          git add BOT/History_Like/ || true
          
          git commit -m "Auto-Save: Update Data Postingan / Sesi Aktif / History Like" || echo "Tidak ada perubahan data"
          git push

      - name: Sapu Bersih Log Server
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list --status completed --limit 15 --json databaseId -q '.[].databaseId' | xargs -I{} gh run delete {} || true
